# Generated by Django 3.2.13 on 2022-07-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
